services:
    _defaults:
        autowire: true
        autoconfigure: true

    SyliusBarionPaymentGateway\:
        resource: '../src/'
        exclude:
            - '../src/SyliusBarionPaymentGatewayPlugin.php'
            - '../src/DependencyInjection/'
            - '../src/Action/'

    sylius_barion.payum.gateway_factory.builder:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            - SyliusBarionPaymentGateway\SyliusPaymentGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: barion_payment }

    sylius_barion.payum.action.convert_payment:
        class: SyliusBarionPaymentGateway\Action\ConvertPaymentAction
        public: true
        tags:
            - { name: payum.action, factory: barion_payment, alias: convert_payment }

    sylius_barion.payum.action.capture:
        class: SyliusBarionPaymentGateway\Action\CaptureAction
        public: true
        tags:
            - { name: payum.action, factory: barion_payment, alias: capture }

    sylius_barion.payum.action.status:
        class: SyliusBarionPaymentGateway\Action\StatusAction
        public: true
        tags:
            - { name: payum.action, factory: barion_payment, alias: status }

    sylius_barion.payum.action.notify:
        class: SyliusBarionPaymentGateway\Action\NotifyAction
        public: true
        tags:
            - { name: payum.action, factory: barion_payment, alias: notify }

    sylius_barion.payum.action.refund:
        class: SyliusBarionPaymentGateway\Action\RefundAction
        public: true
        tags:
            - { name: payum.action, factory: barion_payment, alias: refund }

    sylius_barion.payum.action.cancel:
        class: SyliusBarionPaymentGateway\Action\CancelAuthorizationAction
        public: true
        tags:
            - { name: payum.action, factory: barion_payment, alias: cancel }

    SyliusBarionPaymentGateway\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }
